CFLAGS=-c -Wall -Werror -g -std=c++11

all: stdafx.o interpreter.o throf.o tokenizer.o
	g++ stdafx.o interpreter.o throf.o tokenizer.o stackelement.o -o throf 

stdafx.o: stdafx.cpp stdafx.h
	g++ $(CFLAGS) stdafx.cpp

interpreter.o: interpreter.cpp
	g++ $(CFLAGS) interpreter.cpp

tokenizer.o: tokenizer.cpp
	g++ $(CFLAGS) tokenizer.cpp

stackelement.o: stackelement.cpp
	g++ $(CFLAGS) stackelement.cpp

throf.o: throf.cpp
	g++ $(CFLAGS) throf.cpp
